//
//  AccessibilityLabels.swift
//  QodeX - Comprehensive Accessibility Labels
//  Generated by IVY, CDO - Full Accessibility Audit
//

import SwiftUI

// MARK: - Accessibility Labels Namespace
/// Central repository for all VoiceOver labels, hints, and traits
/// Ensures consistent, meaningful descriptions across the app
public enum AccessibilityLabels {
    
    // MARK: - Dashboard
    public enum Dashboard {
        public static let welcome = "Welcome to QodeX"
        public static let userName = "Welcome, %@"
        public static let membershipBadge = "%@ membership, %@"
        public static let profileAvatar = "Profile avatar for %@, button, double tap to view profile"
        public static let todaysQode = "Today's Qode, number %d, %@"
        public static let todaysQodeHint = "Double tap to view full daily reading"
        public static let exploreButton = "Explore button, double tap to read more"
        public static let quickAction = "%@, %@, button, double tap to %@"
        public static let continueLearning = "Continue Learning section"
        public static let seeAllButton = "See all teachings, button"
        public static let teachingCard = "%@, %@ duration, %d percent complete, button, double tap to continue learning"
        public static let liveSession = "Next Live Session, %@, %@ with %@, button, double tap to set reminder"
        public static let setReminderButton = "Set Reminder, button, double tap to receive notification"
        
        public static func quickAction(title: String, subtitle: String, action: String) -> String {
            return String(format: quickAction, title, subtitle, action)
        }
    }
    
    // MARK: - Calculator
    public enum Calculator {
        public static let title = "Qode Calculator"
        public static let subtitle = "Discover your energetic blueprint"
        public static let birthDateLabel = "Birth Date"
        public static let birthDateHint = "Select your birth date for numerology calculation"
        public static let fullNameLabel = "Full Birth Name"
        public static let fullNameHint = "Enter your full birth name as written on your birth certificate"
        public static let decodeButton = "Decode My Qode, button, double tap to calculate your numerology numbers"
        public static let resultsSection = "Your Qode Matrix results"
        public static let numberCard = "%@ Number %d, %@, button, double tap to view detailed interpretation"
        public static let masterNumberBadge = "Master Number"
        public static let saveProfileButton = "Save to Profile, button, double tap to save these numerology results"
        
        public static func numberCard(title: String, number: Int, description: String) -> String {
            return String(format: numberCard, title, number, description)
        }
    }
    
    // MARK: - Chart
    public enum Chart {
        public static let title = "Your Numerology Chart"
        public static let settingsButton = "Settings, button, double tap to open app settings"
        public static let heroCard = "Your %@ Number %d, %@, %@, button, double tap to view detailed interpretation"
        public static let numberGridCard = "%@ Number %d, %@, button, double tap to view details"
        public static let unlockBanner = "Unlock 5 More Numbers, button, double tap to upgrade and see your complete numerology blueprint"
        public static let selectedState = "Selected"
        public static let unselectedState = "Not selected"
        
        public static func heroCard(type: String, number: Int, title: String, subtitle: String) -> String {
            return String(format: heroCard, type, number, title, subtitle)
        }
    }
    
    // MARK: - Number Detail
    public enum NumberDetail {
        public static let backButton = "Back, button"
        public static let bookmarkButton = "Bookmark, button, double tap to %@"
        public static let bookmarked = "Remove from bookmarks"
        public static let notBookmarked = "Add to bookmarks"
        public static let shareButton = "Share, button, double tap to share this reading"
        public static let heroNumber = "%d, %@, Life Path number"
        public static let keywords = "Keywords: %@"
        public static let aboutSection = "About %@ %d"
        public static let karmicDebtSection = "Karmic Debt %d, The %@"
        public static let coreLesson = "Core Lesson"
        public static let pastLifePattern = "Past Life Pattern"
        public static let howToOvercome = "How to Overcome"
        public static let shadowAspects = "Shadow Aspects"
        public static let growthOpportunities = "Growth Opportunities"
        public static let affirmation = "Affirmation: %@"
        public static let traitsSection = "Traits"
        public static let strengths = "Strengths"
        public static let challenges = "Challenges"
        public static let famousPeople = "Famous Life Path %d's"
        public static let famousPerson = "%@, Life Path %d"
        public static let compatibility = "Compatibility"
        public static let mostCompatible = "Most Compatible numbers: %@"
        public static let challenging = "Challenging numbers: %@"
        public static let careerPaths = "Ideal Career Paths"
        public static let careerOption = "%@ career option"
        public static let relationships = "In Relationships"
        public static let element = "Element: %@"
        public static let tarotCard = "Tarot Card: %@"
        
        public static func bookmarkAction(isBookmarked: Bool) -> String {
            return String(format: bookmarkButton, isBookmarked ? bookmarked : notBookmarked)
        }
    }
    
    // MARK: - Daily Qode
    public enum DailyQode {
        public static let dateHeader = "Today is %@"
        public static let mainNumber = "Today's Qode is number %d, button, double tap to view detailed interpretation"
        public static let mainNumberHint = "Long press to reveal number ring"
        public static let insightCard = "Today's Insight, %@"
        public static let insightDescription = "%@, tap to expand"
        public static let affirmation = "Affirmation: %@, double tap to copy"
        public static let copyButton = "Copy affirmation, button"
        public static let copied = "Copied to clipboard"
        public static let readMoreButton = "Read More, button, double tap to view full reading"
        public static let shareButton = "Share, button, double tap to share your daily Qode"
        public static let favoriteButton = "Favorite, button, double tap to add to favorites"
        public static let weeklyPreview = "This Week's energy preview"
        public static let dayPreview = "%@, number %d, %@"
        public static let todayIndicator = "Today"
        public static let viewCalendarButton = "View Calendar, button"
        public static let energyForecast = "Energy Forecast, %d percent, %@ vibrational day"
        public static let trendRising = "Rising %d percent"
        public static let trendFalling = "Falling %d percent"
        public static let trendStable = "Stable"
        public static let activityPositive = "%@, recommended activity"
        public static let activityNegative = "%@, activity to avoid"
        public static let sectionToday = "Today's Energy section"
        public static let sectionBestActivities = "Best Activities section"
        public static let sectionAvoid = "Things to Avoid section"
        
        public static func dayPreview(day: String, number: Int, isToday: Bool) -> String {
            let suffix = isToday ? ", Today" : ""
            return String(format: dayPreview, day, number, suffix)
        }
    }
    
    // MARK: - Main Tab Bar
    public enum TabBar {
        public static let today = "Today tab, button"
        public static let chart = "Your Chart tab, button"
        public static let calculator = "Calculator tab, button"
        public static let community = "Community tab, button"
        public static let profile = "Profile tab, button"
        
        public static let todayHint = "Double tap to view today's numerology reading"
        public static let chartHint = "Double tap to view your complete numerology chart"
        public static let calculatorHint = "Double tap to calculate new numerology numbers"
        public static let communityHint = "Double tap to connect with the QodeX community"
        public static let profileHint = "Double tap to view and edit your profile"
    }
    
    // MARK: - Settings
    public enum Settings {
        public static let title = "Settings"
        public static let notifications = "Notifications, %@"
        public static let notificationsOn = "enabled"
        public static let notificationsOff = "disabled"
        public static let dailyReminder = "Daily Reminder, %@"
        public static let reminderTime = "Reminder time, %@"
        public static let soundEffects = "Sound Effects, %@"
        public static let haptics = "Haptic Feedback, %@"
        public static let reduceMotion = "Reduce Motion, %@"
        public static let highContrast = "High Contrast, %@"
        public static let textSize = "Text Size"
        public static let privacy = "Privacy"
        public static let termsOfService = "Terms of Service"
        public static let privacyPolicy = "Privacy Policy"
        public static let help = "Help & Support"
        public static let about = "About QodeX"
        public static let version = "Version %@"
        public static let signOut = "Sign Out, button"
        public static let deleteAccount = "Delete Account, button"
    }
    
    // MARK: - Onboarding
    public enum Onboarding {
        public static let welcomeTitle = "Welcome to QodeX"
        public static let welcomeMessage = "Discover the hidden patterns in your life through the ancient wisdom of numerology"
        public static let nextButton = "Next, button"
        public static let getStartedButton = "Get Started, button"
        public static let skipButton = "Skip, button"
        public static let pageIndicator = "Page %d of %d"
    }
    
    // MARK: - Paywall / Subscription
    public enum Subscription {
        public static let upgradeTitle = "Unlock Your Full Potential"
        public static let monthlyPlan = "Monthly Plan, %@ per month"
        public static let yearlyPlan = "Yearly Plan, %@ per year, save %@ percent"
        public static let lifetimePlan = "Lifetime Access, one-time payment of %@"
        public static let subscribeButton = "Subscribe, button, double tap to start subscription"
        public static let restoreButton = "Restore Purchases, button"
        public static let termsButton = "Terms and Privacy, button"
        public static let featureList = "Premium features include: %@"
        public static let featureItem = "%@, included"
    }
    
    // MARK: - Community
    public enum Community {
        public static let feedTitle = "Community Feed"
        public static let post = "Post by %@, %@"
        public static let likeButton = "Like, %d likes, button"
        public static let commentButton = "Comment, %d comments, button"
        public static let sharePostButton = "Share post, button"
        public static let newPostButton = "New Post, button"
        public static let userAvatar = "%@'s profile picture"
    }
    
    // MARK: - Search
    public enum Search {
        public static let searchField = "Search, text field"
        public static let searchHint = "Type to search teachings, readings, or community posts"
        public static let clearButton = "Clear search, button"
        public static let resultItem = "%@, %@"
        public static let noResults = "No results found for %@"
    }
    
    // MARK: - Notifications
    public enum Notifications {
        public static let title = "Notifications"
        public static let dailyReading = "Daily Reading Available"
        public static let dailyReadingMessage = "Your numerology reading for today is ready"
        public static let liveSession = "Live Session Starting Soon"
        public static let liveSessionMessage = "%@ starts in %d minutes"
        public static let achievement = "Achievement Unlocked"
        public static let achievementMessage = "You earned: %@"
        public static let markRead = "Mark as read, button"
        public static let dismiss = "Dismiss, button"
    }
    
    // MARK: - Achievement / Streaks
    public enum Achievements {
        public static let currentStreak = "Current streak, %d days"
        public static let longestStreak = "Longest streak, %d days"
        public static let achievement = "%@ achievement, %@"
        public static let locked = "Locked achievement, %@"
        public static let unlocked = "Unlocked achievement, %@, earned on %@"
    }
    
    // MARK: - Loading States
    public enum Loading {
        public static let calculating = "Calculating your numerology numbers"
        public static let loading = "Loading"
        public static let saving = "Saving to profile"
        public static let refreshing = "Refreshing"
        public static let error = "Error loading content"
        public static let retryButton = "Retry, button"
    }
    
    // MARK: - Generic UI Elements
    public enum UI {
        public static let closeButton = "Close, button"
        public static let doneButton = "Done, button"
        public static let cancelButton = "Cancel, button"
        public static let saveButton = "Save, button"
        public static let deleteButton = "Delete, button"
        public static let editButton = "Edit, button"
        public static let backButton = "Back, button"
        public static let moreOptions = "More options, button"
        public static let expand = "Expand, button"
        public static let collapse = "Collapse, button"
        public static let scrollView = "Scrollable content"
        public static let pullToRefresh = "Pull down to refresh"
        public static let swipeToDismiss = "Swipe down to dismiss"
    }
}

// MARK: - Accessibility Traits Helper
public struct AccessibilityTraits {
    public static let button: AccessibilityTraits = .isButton
    public static let header: AccessibilityTraits = .isHeader
    public static let link: AccessibilityTraits = .isLink
    public static let selected: AccessibilityTraits = .isSelected
    public static let image: AccessibilityTraits = .isImage
    public static let staticText: AccessibilityTraits = .isStaticText
    public static let searchField: AccessibilityTraits = .isSearchField
    public static let keyboardKey: AccessibilityTraits = .isKeyboardKey
    public static let adjustsValue: AccessibilityTraits = .adjustable
    public static let updatesFrequently: AccessibilityTraits = .updatesFrequently
    public static let startsMediaSession: AccessibilityTraits = .startsMediaSession
    public static let playsSound: AccessibilityTraits = .playsSound
    public static let allowsDirectInteraction: AccessibilityTraits = .allowsDirectInteraction
    public static let causesPageTurn: AccessibilityTraits = .causesPageTurn
}

// MARK: - Accessibility Priority
public enum AccessibilityPriority: Double {
    case low = 0.5
    case medium = 1.0
    case high = 2.0
    case critical = 3.0
}
